version: "3"

services:
  routeoptimizationws:
    build:
      context: .
      dockerfile: Dockerfile
    command: sh -c "uvicorn main_api:app --host 0.0.0.0 --port 8004 --reload" # ini untuk api
    # command: sh -c "python3 main.py"
    image: routeoptimization:latest
    container_name: routeoptimization
    ports:
      - "8004:8004"
    volumes:
      - ./app:/code
    environment:
      - PYTHONUNBUFFERED=1
